# Generated by Django 5.2 on 2025-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiredemployee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='hiredemployee',
            name='job',
        ),
        migrations.AddField(
            model_name='hiredemployee',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiredemployee',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
